### ISSUE TITLE
[Question] how to fetch the body annotation?

### ISSUE THREAD

**Issue by jingpengw** [janelia-flyem/neuclease#14]
Our proofreaders have made body annotations for objects in Glia cells using NeuTu.
Is that possible to fetch this annotation either as a list of body IDs or a plane segmentation? 

I checked the unit test code, and did not find any corresponding function.

**Comment by stuarteberg** [comment]
Assuming they made the annotations with NeuTu, then they'll be stored in an instance named `{labelmap_name}_annotations`.  For instance, if your main segmentation is stored in a `labelmap` instance named `segmentation`, then look in the `segmentation_annotations` instance.  If your main segmentation is stored in an instance named `labels`, then look in `labels_annotations`.

All annotations for each body are stored together in a single JSON object value for the body, whose key is the body ID.

For example, here are the annotations for a randomly chosen body in the hemibrain:

```python
In [3]: from neuclease.dvid import fetch_key
   ...: fetch_key(
   ...:     'https://hemibrain-dvid.janelia.org',
   ...:     '31597d95bd844060b0ccc928a1a8a0a4',
   ...:     'segmentation_annotations',
   ...:     671233447,
   ...:     as_json=True
   ...: )
Out[3]:
{'body ID': 671233447,
 'class': 'AVLP176_a',
 'comment': 'hemi brain whole 20K to 30K',
 'instance': 'AVLP176_a_R',
 'naming user': 'takemuras',
 'primary neurite': 'AVL03',
 'status': 'Roughly traced',
 'user': 'takemuras',
 'cell body fiber': 'AVL03'}
```

There is also a convenience function in `neuclease` for fetching many annotations and loading them into a DataFrame.

```python
In [10]: from neuclease.dvid import fetch_body_annotations
    ...:
    ...: bodies = [577455404, 1012660884, 1043022708, 1044343952, 1072715232, 1074333284, 1136472342]
    ...: ann = fetch_body_annotations(
    ...:     'https://hemibrain-dvid.janelia.org',
    ...:     '31597d95bd844060b0ccc928a1a8a0a4',
    ...:     'segmentation_annotations',
    ...:
    ...:     # If you provide no body list, then all annotations are fetched.
    ...:     bodies=bodies,
    ...:
    ...:     # If you have non-standard status categories,
    ...:     # then you can't use the default ones.
    ...:     status_categories=None
    ...: )
    ...:
    ...: ann[['status', 'instance']].head()
Out[10]:
                    status   instance
body
577455404   Roughly traced  AVLP127_R
1012660884          Leaves        NaN
1043022708  Roughly traced  AVLP071_R
1044343952  Roughly traced  AVLP170_R
1072715232  Roughly traced    CL350_L
```

---

PS -- Traditionally, we used a `keyvalue` instance for storing such annotations, but in recent years we upgraded to a new DVID instance type that is dedicated to holding such annotations.  Instead of `keyvalue`, it's called `neuronjson`.  But either way, the name of the instance will be the same (`labels_annotations`).  The API for `neuronjson` is mostly the same as the `keyvalue` instance, but it's a bit faster, and it supports special queries.

**Comment by jingpengw** [comment]
thanks a lot! The examples are helpful, but they all require body IDs.
I do not know which bodies are annotated. Actually, I need to know which bodies are annotated as glia cells.
Is there a method to fetch all the annotations and then I can filter the glia cells out?

**Comment by stuarteberg** [comment]
PPS -- To see which keys are currently contained in the instance, you can use `bodies=None` with the convenience function above, or more generally (since it's just a `keyvalue` instance) use ` GET .../keys`:

```python
from neuclease.dvid import fetch_keys
all_keys = fetch_keys(
    'https://hemibrain-dvid.janelia.org',
    '31597d9',
    'segmentation_annotations'
)
```

Or, equivalently:

```python
import requests
url = 'https://hemibrain-dvid.janelia.org/api/node/31597d/segmentation_annotations/keys'
all_keys = requests.get(url, params={'user': 'jingpengw'}).json()
```

**Comment by jingpengw** [comment]
thank you! I have figured it out!
